from scraper import VehicleScraper
from pprint import pprint


def main():

    keyword = "Toyota Hilux"

    scraper = VehicleScraper()

    try:

        print("=" * 70)
        print("Mbare Marketplace Vehicle Scraper")
        print("=" * 70)

        print(f"\nSearching for: {keyword}\n")

        scraper.start()

        vehicles = scraper.scrape_search_results(keyword)

        print(f"\nVehicles Found: {len(vehicles)}\n")

        for i, vehicle in enumerate(vehicles, start=1):

            print("=" * 70)
            print(f"Vehicle {i}")
            print("=" * 70)

            pprint(vehicle)

    except Exception as e:

        print("\nSCRAPER ERROR")
        print(e)

    finally:

        scraper.stop()

        print("\nScraper Finished")


if __name__ == "__main__":
    main()
